### ISSUE TITLE
coatdemo is down

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#112]
502 Bad Gateway on coatdemo.coat.no

**Comment by frafra** [comment]
That happens because on the 15th of each month the server is restarted and coatdemo is not automatically started because of an issue on the specific server we are using for testing.

It looks like thanks to the recent upgrades it has been partially fixed.

@mdlux we can now use Portainer to deploy coatdemo, but it does not support compose files v3, just v2, so I had to remove the Postgres health check. ckan also fails if solr is not up yet, so it needs to be restarted manually.
