### ISSUE TITLE
Resource citation author should not be email address, but name

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#129]
In the resource citation of datasets, protocols and also the data management plan, the name of the author is indicated by the email address. This should be changed to the name of the author/owner.

**Comment by frafra** [comment]
We get the full name from UNINETT Feide authentication mechanism. The citation now looks like this (on coatdemo, when creating or updating a dataset):
>  Name Surname et al., 2022, test_v1: COAT project data.

I guess it would be better to have `N. Surname` or similar, but that would require knowing what is the name and what is the surname, which is not trivial, since some people could have more than one name or surname.

I am closing the issue, but do not hesitate to open a new one to improve the citation text.
