### ISSUE TITLE
version "_v1" suffix appended twice

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#26]
See:
https://coatdemo.frafra.no/dataset/v_rodents_snaptrapping_individuals_intensive_v1_v1

**Comment by eevasoininen** [comment]
It happened when I tried to create a dataset. I had written everything and uploaded a file, and then I got a message that I could not make a public dataset. I tried to go back to modify my choise between private/public, but was not able. I then made (I thought) a dataset with the same name but an with "_test" added. But something happened with the naming.

**Comment by frafra** [comment]
Thanks for the details Eeva. This kind of behaviour happens if something fails between the creation of the dataset and the versioned dataset. I am working on that to handle that scenario.

**Comment by frafra** [comment]
Ok that happened because a public dataset has been created, then resources have been added in the second step, but a public dataset cannot be modified by design (public datasets have DOI and are immutable). Users should not be allowed to create public datasets at the very beginning then, but they should make them public after they uploaded all the resources and they are OK releasing the whole dataset to the public.

It is possible to amend data in extraordinary situations by setting the dataset as private and then re-releasing it setting the visibility to public.

**Comment by eevasoininen** [comment]
Sounds good. Maybe the whole field could be removed, and one could rather have an option of "save draft dataset" in earlier phase, and then when one is done "publish dataset". Or something like that? Now it was not intuitive :)

**Comment by frafra** [comment]
It is not intuitive and having a different button just for that would be better. I can do that.

**Comment by eevasoininen** [comment]
This should be kept open; when I tried to re-create a public dataset and then go back to edit it to make it private, I get v1_v1. The same does not happen if I go back to edit other information.

**Comment by frafra** [comment]
I still get this _v1_v1_v1 problem, which has to be further investigated, which is related to the field auto-completion only at the moment.

**Comment by frafra** [comment]
Fixed :-)
