### ISSUE TITLE
Memorize previous form records while adding multiple resources to a dataset

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#27]
To avoid rewriting multiple times the same information to metadata of a new resource, using the GUI, it would be nice to keep memory of text added previously. such text would be partially  modified (instead of completely rewritten). This is the case for example of reources names, which will be often the same name as the dataset + a "year" suffix.

**Comment by frafra** [comment]
Browsers should already have the option to select the latest strings typed in, but that could be not enough I suppose.

Prefilling the fields could be a bit too strong (people could make mistakes, error because of duplicates values etc.;) so I would suggest to still ask for user input with some help. A clickable link/button could fill the text field with the suggested value based on session cookies maybe.
