### ISSUE TITLE
Use dd/mm/yyyy or yyyy/mm/dd instead of mm/dd/yyyy

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#29]
Hei, I was trying to manually type in a date (27/07/2005). What happened was that instead of 27 I got 02/07. I was able to manipulate the date through clicking via the visual calendar, though.

**Comment by janeuhd** [comment]
I think your problem is that the format is mm/dd/yyyy. You typed dd/mm/yyyy and your '27' was hence not valid.
@frafra: could we change date format to a more intuitive order? Either yyyy/mm/dd or the reverse?

**Comment by eevasoininen** [comment]
Indeed its possible that was the issue. I tried again today with month (number max 12) and it works.

**Comment by frafra** [comment]
@janeuhd It is not intuitive indeed. I will keep this issue open and try to improve that.

**Comment by frafra** [comment]
All the dates are stored as US dates, including embargo even if it wasn't meant to be. I will focus on the user interface as it seems the best option to me.

**Comment by frafra** [comment]
It seems that your browser locale/language is not properly set. This affect the format of the date you see, while it does not affect how the date is stored in the database.

Microsoft Edge on my PC shows the date as "dd.mm.yyyy". This is the solution that should be available by default on every NINA PC. If you are using the default browser and it is not setup properly, I suggest to inform datahjelp about that.

As I mostly use Firefox, I installed it by myself and I have seen that Firefox shows the date as "dd.mm.yyyy" if the language is set to Norwegian Bokmål, but it does not if it set to "English (United States)".

A proper solution would be to setup your favourite language/locale so the browser can show you the date and the date picker in the format you prefer and ask for help to datahjelp if needed. There is no trivial way to override this behaviour, as that is how it is meant to be; otherwise it would be necessary to have a custom input system which would require quite an important amount of extra work and it would be just a workaround that would not integrate well with your browser and device (try to edit a dataset from a tablet or smartphone to see how the date picker is able to adapt to your device, as it is managed from the browser itself).

**Comment by janeuhd** [comment]
It works for me. I had to change the universal language settings though, was not allowed to change settings just for Edge. But now the portal shows date format as dd/mm/yyyy on all browsers.

**Comment by eevasoininen** [comment]
The portal shows mm/dd/yyyy in my browser (firefox, some sort of english). If its too difficult to change it so that everyone would see dd-mm-yyyy (or inverse) without having to play with their settings its probably easiest to leave it be. I doubt most people are interested in taking time to change their settings just for this.
