### ISSUE TITLE
Spatial search broken? (was: Metadata interface - locations)

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#34]
Here it was possible to choose only one location? I see that Jane managed to choose several. I was only able to choose one, so I took the one that covers all necessary areas (subregion). I then searched through the map solution, drawing a square around one of the locations included in the dataset. No dataset came up.

**Comment by frafra** [comment]
The previous interface was not intuitive, because it required to use CTRL to select multiple locations at once. I just implemented an auto-complete form for multiple locations which you should be able to see on the demo instance.

Spatial indexing should work, but I will do more test on that. If you could gave me a link to a specific dataset which shows the problem we can figure out what is happening more quickly.

**Comment by eevasoininen** [comment]
It works now to choose several :) Could the info be changed to: 
" Data collection location. Choose the most detailed possible. You can also choose several." 
I'll see how the map works after trying this.

**Comment by frafra** [comment]
Sure, text changed too. We will also do a bit of cleanup and minor improvements with respect to labels and descriptions in general.

I guess the issue you have with the spatial search will persist and I will have to investigate why is that, as this looks like a regression to me; after much time spent to make it work it would be a real pity not to be able to use it :)

**Comment by eevasoininen** [comment]
I tried this again; adding several locations on a dataset, and then searching on the map-interface in a sub-area where these are. Three datasets came up. These three have the specific sub-area listed in the "Geographic location". Two datasets that also have data from the area, but only list a higher-level location did not come up.

**Comment by janeuhd** [comment]
I found a related issue. The datasets tagged anything to do with 'Polmak'  (Varanger-Rakkonjarga-Polmak-..) does not show up when the bounding box on the map is placed around Polmak. Presumably the bounding box for Varanger-Rakkonjarga is too small? Would it be easy to produce a map of the bounding boxes used, so that we could check whether everything is included? @frafra

**Comment by frafra** [comment]
@janeuhd locations are just points provided to us previously, while selecting multiple locations produces a bounding box which includes all the points (taking minx/miny maxx/maxy of all selected locations each time). I wonder if this issue could be somehow related to these pointy bounding boxes.

**Comment by janeuhd** [comment]
@frafra I'm not sure. The Polmak datasets have the location given all the way down to section (4 levels, for instance varanger/rakkonjarga/polmak/polmak_norway). And in the coordinate file we only included coordinates for the upper 3 levels (as we agreed at the time). That means that we have coordinates for polmak, but not for polmak_norway. Could the problem be that datasets with location given with 4 levels end up without coordinates, rather than with the coordinates of level 3 (and hence does not show up inn spatial search)?

**Comment by frafra** [comment]
@janeuhd I do not think so, because even 4th level location are associated to a point.

I was able to confirm my guess: the problem only happens with bounding box covering a single point. I will just add a negligible buffer to fix this issue.

**Comment by frafra** [comment]
I deployed the patched version and I updated all the datasets (without doing any change to them) just to refresh their geometries. It seems fixed to me now.

I also see that spatial search could return the same dataset multiple times because it can have multiple versions (with different geometries theoretically). I opened a separate issue for that: #58.
