### ISSUE TITLE
Resource filename should be prefilled (was: Metadata solution - file names)

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#36]
Should the file name be automatically the file name that one has uploaded? With a possibility to modify it?

**Comment by frafra** [comment]
It looks to me that the software we use as base already have this functionality, but something is broken at the moment.

**Comment by eevasoininen** [comment]
It does not work at the moment when I have tried again.

**Comment by frafra** [comment]
This is an issue with the extension we are using: https://github.com/ckan/ckanext-scheming/issues/223
I will develop a fix or a workaround at least in the meanwhile.

**Comment by frafra** [comment]
Minor issue mitigation: the application no longer accepts empty filenames, so the users cannot forget about writing down the name.

**Comment by frafra** [comment]
Added link to fill name field based on filename or URL. That, combined with the validation check for the empty name field, could be enough to fix this issue.

I preferred to avoid prefilling without any user input because the information could be overwritten automatically and I generally prefer being explicit and be sure that the user is aware of what it is happening.
