### ISSUE TITLE
Metadata solution - public and private datasets

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#37]
We need more information and help what these mean, to be able to choose correctly; i.e. i) who can see private data and who can see public data, ii) if its possible to change afterwards.

I was currently not allowed to make a public dataset.

**Comment by frafra** [comment]
You are not able to create a public datasets with resources because of that: https://github.com/COATnor/COAT_portal_issues/issues/26#issuecomment-551067302

In addition to removing the ability to choose visibility of the dataset at the very beginning, a good description should be added to the visibility field, to inform user about the limitations related to having a dataset set as public.

- Public dataset
  - Metadata is available to everybody
  - Resources is available only if embargo is not set or is expired
- Private dataset
  - Module editors can see and modify
  - Module members can only see
  - Users cannot see

Administrators can do everything.

The mechanism to avoid changes to public versioned datasets (without setting them to private first) applies to all the users, including administrators. Please be aware that different versions can have different visibility and different embargo.

**Comment by eevasoininen** [comment]
This should stay open. The info listed above by @frafra on what is private and what is public should be here. 

We have discussed it in another thread (#26): 
- the current solution is not intuitive
- instead, have option to save draft dataset and publish a public version of dataset?

Currently I also do not see how does it work to change the status of a dataset from private/draft to public. So the whole process of what the concepts are, and how to create a dataset draft and then a public version should be explained/clarified.

**Comment by frafra** [comment]
Draft is an intermediate status; dataset in the process of being created are marked as "draft".

Fixes implemented:
- Help text added (this fixes the requests)
- Users can no longer flag a dataset as public during its creation to avoid errors due to impossibility to add new resources to public datasets
- If the user tries to flag a new dataset as public, an error will appear with a suggestion to set it to private

**Comment by frafra** [comment]
The current solution seems enough for me at the moment.

Having proper documentation and eventually use a special button for that could improve the user experience, even if I would prefer having too many special buttons around to handle data.

**Comment by eevasoininen** [comment]
Hei, I do not see any help text. Where did you add that? I also still have the option to select "public" while creating a dataset; if this should not be possible wouldn't it be better to remove it? There should be at least something explaining what is private, what is public, what to choose when creating and versioning a dataset and where/when/how to change the status to public.

**Comment by frafra** [comment]
Hei,
sorry Eeva, I just added it back, it slept away with some other changes we made. I do not know if the description I wrote is enough.
I also hidden the field entirely during the creation of a new dataset as you suggested.
