### ISSUE TITLE
Tag autocompletion mechanism regression (was: Metadata solution - editing bug?)

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#41]
I tried to edit metadata of dataset "V_rodents_snaptrapping_individuals_intensive_new_try". 
Went through "manage" buttom to this page:
https://coatdemo.frafra.no/dataset/edit/v_rodents_snaptrapping_individuals_intensive_v1_v1
After clicking "Update dataset" button at the bottom I go this message: "Server Error An internal server error occurred"

**Comment by frafra** [comment]
Thanks for the feedback Eeva.

This is related to #26. I am taking care of it.

**Comment by eevasoininen** [comment]
OK, now I got the same message also when trying to add a new dataset.

**Comment by frafra** [comment]
Ok, I am sorry, that is a regression related to #31. I am fixing it.

**Comment by frafra** [comment]
Fixed, sorry for having introduced a regression. The "tags" field is now handled a bit differently from the other autocomplete fields (because of CKAN internals), but there should be no difference at all for users.

As usual, you can close the issue when you think the problem has been solved. Thank you for your patience and feedback :-)

**Comment by eevasoininen** [comment]
This seems to be fixed now: I was able to open a dataset through "manage" button, change some metadata, and save the changes.
