### ISSUE TITLE
Scientific names does not show in the search result

### ISSUE THREAD

**Issue by rbj015** [COATnor/COAT_portal_issues#48]
Should it be possible to search for scientific names in the search field, and get data sets containing those names in return? I have added "lagopus sp (rype)" as a scientific name to one data set, but it does not show when searching for e.g. "lagopus" in the search field.

**Comment by janeuhd** [comment]
That is true. We need that functionality added. The search function should search all metadata fields. @frafra @mdlux

**Comment by rbj015** [comment]
Also: if you have assigned a detailed geographic location level to a data set, e.g. "Varanger - Varjjatnjarga - Vestre Jakobselv", a search for a higher level (e.g. Varjjatnjarga) will not return this data set. I am not sure if this is also a problem @janeuhd?

**Comment by frafra** [comment]
That the full label is not stored in the metadata, just the abbreviation is searchable or filtered at the moment. Same thing applies to locations. I can work on that.

I suggest to open a different issue to discuss if the application should add higher level locations automatically or not.

**Comment by eevasoininen** [comment]
I can currently search with the abbreviations "lag_sp" results in datasets, while "lagopus" does not.

**Comment by janeuhd** [comment]
@frafra 
The application should add all levels of locations. A dataset labelled "Varanger - Varjjatnjarga - Vestre Jakobselv", should be returned in a search on all three terms separate as well as the total term.

**Comment by frafra** [comment]
@janeuhd ok, thanks for the clarification, I will add a mechanism which select higher level locations when the user edits/saves a dataset.

**Comment by frafra** [comment]
@janeuhd Mechanism implemented, dataset updated.

@eevasoininen I would use filters on the left for that (see: #55)

If you agree on that, I would propose to close this specific issue.

**Comment by janeuhd** [comment]
The location search seems to work on all levels. But I think the issue persists that the species names added to the metadata are not searchable?

**Comment by frafra** [comment]
They are not indeed. I would suggest to use filters for species (#55), locations and tags in general. Does it seems acceptable? I can look into improving that, but there are some technical limitations to overcome related to the software we are relying on.

**Comment by eevasoininen** [comment]
Im sorry, I dont understand what you mean with using filters here? 

What we wanted was that independent of whether one searches lagopus or lag_sp the dataset would show up. It is very unlikley that anyone outside COAT would search with other names than complete family/genus/species names.

**Comment by frafra** [comment]
@eevasoininen that is for sure. Sorry if I did not explained it properly; with "filters" I mean the filters/tag lists that you have on the left bar. If someone would look for a dataset related to some species, it could select the tags on the left instead of searching on the main bar, which is meant to be a way to look for titles and descriptions more than tags.

I can understand this is not optimal, but I wanted to check with you if that is acceptable or it you think that is important and/or urgent to have a search field which can also look into tags or not (without abbreviations of course). I think that it is feasible with a workaround, but it could require probably around 1~2 extra day of work and there are various issues open that I am trying to fix as quick as I can, so it would be good to have an idea about your priorities.

**Comment by frafra** [comment]
It is now possible to select full names (labels) on the left instead of abbreviations, both for locations and scientific names (see #59). It should be more intuitive.

**Comment by frafra** [comment]
Sorry for the high number of comments on this discussion, I hope that does not bother you.

I am glad to let you know that all the issues we discussed here have been fixed. The search bar can be used to look for locations and/or genus, abbreviations are not used at all (even at the database level) and the search filters for scientific names and location are available on the left bar and they seem to work as expected.

There is still a naming problem (how the tags should be named from species/genus/...), but I created a different issue for that: #61.

I am going to close this issue, but feel free to reopen it if you think the problem was not solved.
