### ISSUE TITLE
Unique identifiers for scientific names

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#61]
Hei @janeuhd,
there is a problem with respect to the unique identifiers for scientific names. As you know, we create a label containing family, specie, genus, latin, and norwegian name, while we skip fields that are not available.

In order to make this information searchable, we need to have a meaningful unique identifier for each element, like a tag. I tried to use the most precise name available (for example, if a element has a label with family, specie and genus, I use genus as unique identifier). The problem is that sometimes there are elements with same genus but different specie, and that causes issues. For example, "Betula" appears twice.

Do you think it would be possible to define a good human-readable, meaningful and unique identifier (tag) for each element? I can define a set of rule to extract this information instead of creating a new column in the taxonomy files if you want.

**Comment by janeuhd** [comment]
@frafra I'm not entirely sure I understand what the problem is, so forgive me if I have misunderstood. First a comment: it is only now that I realize that the label is put together in the wrong order (e.g. family - species - genus). It should be family - genus - species, as the species is the most precise name, not the genus.

Then to the unique ID: Can not the latin species name be the unique identifier? They are per definition unique. If the unique ID has to be a string without spaces, then presumably the abbreviation can be used? They are unique as well (if not it is a mistake that can be corrected, they have to be unique).

Have I understood the issue correctly?

**Comment by frafra** [comment]
Thanks Jane, for the explanation.

I could use the species name as unique identifier, but there is a case where the same value appears twice: "Stenichnus bicolor" belongs to both the "Scydmaenidae" and the "Staphylinidae" families.

With respect to Norwegian and English nomenclature, do you think it could be useful to have it in the label? At the moment I am adding the Norwegian name between parenthesis, but I could add the English name too or avoid local names entirely if you prefer.

**Comment by janeuhd** [comment]
I think it would be good to have both UK and NO names when they are available.
The species you mention must have been added twice by mistake. I'll sort it out!

**Comment by frafra** [comment]
Ok I fixed the taxonomy and added the English names too. I disabled the Stenichnus bicolor from the Scydmaenidae family for the moment.

**Comment by frafra** [comment]
Thanks @opl100! So I guess we are done here.

Feel free to open a new issue in case the taxonomy list needs to be updated/synchronized with your `_final.csv` files on Box.
