### ISSUE TITLE
State variables on data portal

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#74]
These are variables which are calculated from COAT data sets and which should be added to the portal and made available in the same way as raw datasets, but clearly tagged as state variables (e.g. processed data). How do we best automatize that calculation and updating of state variables from  datasets?

TODO @mdlux : add new tab for “state variables” in the portal

TODO @mdlux : State variables will have a slightly different set of metadata relative to primary datasets (must for instance include a link to which data sets they are based on, both those requested from the COAT data portal, and from external services such as MET). Implement state variable metadata fields.

TODO @janeuhd : calculate an example of a state variable from primary data sets (moth data)

To think about: can we think about an automatic way of updating state variables when a data set is updated? This will usually be once a year. A fixed date for updating state variables for instance twice a year?

**Comment by frafra** [comment]
@janeuhd 
As _states variables_ will be a special type of datasets, shown in a different tab and with different metadata schema, some questions arise:
1. Should state variables be linked to one or more _versioned_ datasets or to _non-versioned_ datasets, which would point to the latest public version (which could be under embargo)?
2. Should state variables be versioned like regular datasets?
3. Which metadata fields should be stored?
4. Which metadata fields could be automatically filled?

**Comment by janeuhd** [comment]
State variables are always linked to versioned datasets and should be versioned themselves in the same way as regular datasets. They can exist in both public and private versions in the same way as regular datasets. A state variable is only made public for a given time period if the data it is based on is also public. For example:
Dataset A is under 2 years embargo and hence exist in 3 versions in the portal:
-v1 is public and covers 2000-2018
-v2 is private and covers 2000-2019 (release date 2021)
-v3 is private and covers 2000-2020 (release date 2022)

A state variable based on dataset A will always exist in a public version based on the most recent public version of the dataset (in this example dataset A v1). But for some state variables we might need private versions for internal use (in this example based on dataset A v2 or v3).
Note that some state variables might be based on several different datasets. 

For the metadata I think we can keep almost the same list as for dataset, but add a new field where one can select which datasets (public or private) the state variable is based on. It would be great if this field could list all available datasets as a drop down. The two fields 'Funding source' and 'Study protocol' are not strictly relevant for state variables, but if it is easier to keep the same list as for the datasets then they can stay. 

I guess many of the fields for state variables could be automatically filled if the info can be collected from the metadata for the contributing dataset? However, the following fields would always differ: 

- Description (should be a description of the state variable, not the associated datasets), 
- Associated scripts (should link to the script calculating the state variable from the data) 
- Bibliographic citation: should cite papers/reports using the state variable, not just the contributing data.
- Resource citation: should be the citation of the state variable, not the datasets.

I'm unsure how automatic filling would work if a state variable is based on two datasets? I think it might be messy, if for instance we have two contact persons (one for each dataset) and generate a resource citation from this? So I wonder, if state variable metadata field should only be filled in automatically if we have one contributing dataset?

**Comment by frafra** [comment]
It is not possible to guarantee that the version number of state variables datasets and dataset will match, because a state variables datasets can depend on one or more datasets which can have different versions, but I think this is not so important.

It is not a problem to remove/add metadata fields for state variables.

We cannot blindly copy metadata from a singular dataset, as we could have more than one; some metadata could be merged somehow, like this:
- embargo/visibility: use the most conservative embargo/visibility between all the versioned dataset involved
- start date: copy the start date value of the oldest dataset
- end date: copy the end date value of the oldest dataset
- geographic location: create a bounding box which includes the bounding boxes of all the linked datasets
- scientific name, tags, associated parties, persons: join the linked datasets correspondent fields
- resource citation: add all the authors from the various datasets
- topic category code, contact person, license, organization name: should we transform each one of those fields into multiple values fields to keep all the initial information?

Another possibility would be to reduce the amount of metadata stored in the state variables and refer to the datasets for additional information, but that could affect the ability to search for them based on which fields we decide to keep and which ones are not relevant (for example, no scientific names/tags/locations would mean no filters in the search page). In this case I think that at least license and resource citation need to be kept and automatically copied/merged from the initial datasets.

**Comment by janeuhd** [comment]
Since we only have search capabilities on the metadata level, I think it is important to keep a fairly rich metadata list also for state variables. I think we can do as you suggest, and edit/fill in the blanks manually.

- embargo/visibility: use the most conservative embargo/visibility 

- start date: copy the **newest** start date value since the state variable will only cover years where ALL required data are available

- end date: copy the **oldest** end date value 

- geographic location: create a bounding box which includes the bounding boxes of all the linked datasets

- scientific name, tags, associated parties, persons: join the linked datasets correspondent fields

- resource citation: I think the author for all state variables should simply be "COAT" 

- topic category code, contact person, license, organization name: should we transform each one of those fields into multiple values fields to keep all the initial information? YES, as long as we can handle the cases where the value is the same for both/all datasets (e.g. we do not want contact person to be "Jepsen; Jepsen", if we use two datasets with me as a contact person).

**Comment by frafra** [comment]
Ok. I will implement the schema for the state variables by tomorrow and try to have it on a test environment shortly after that, so we can still deploy the software in the production before the end of the month.
Automatic filling of fields based on datasets will implemented during the second half of February probably.

**Comment by frafra** [comment]
It is now possible to add "States" datasets on coatdemo.

I kept license as a single-value field because producing a dataset from two datasets with different license, it does not mean that the resulting license is an addition or combination of the two. The default CC-BY license is kept for simplicity.

**Comment by janeuhd** [comment]
Thanks. Some immediate adjustments: 
- We need them to be called 'State variables', not just 'States'. In ecology a single 'State' (tilstand) would be described by multiple 'State variables' (tilstandsvariabler).
- It would be preferably if state variables could be added as a separate tab in the menu (e.g. 'Datasets', 'State variables', 'Modules', 'About'). Also state variables needs a counter Under COAT data portal statistics on the front page. 
- When you click on 'Create state' the page info still refers to 'Datasets'. Could this be changed to 'State variables'? I'll write a short description which can be added to describe 'What is a state variable' in the left pane. At the moment it reads 'What is a dataset' also under state variables.
![image](https://user-images.githubusercontent.com/35291431/73282520-0cbfaa00-41f2-11ea-902d-66066166d467.png)


We hope that many of the state variables can be updated automatically when new versions of the underlying data are created. But we can return to this. We need this option for manual upload no matter what.

**Comment by frafra** [comment]
- Renaming can be done without any problem
- I am already working on this (it is not available on coatdemo due to a small graphical glitch I am trying to solve)
- We can use a different text when ready

Automatic updates will be possible with an additional mechanism; having defined a clean structure for the metadata and the relation between datasets and state variables serves as a sound foundation.

**Comment by frafra** [comment]
Fixed on coatdemo.

**Comment by janeuhd** [comment]
I can't access the demo just now (Bad gateway). Will try a bit later.

**Comment by frafra** [comment]
Sorry, I was deploying a minor update (and there is a ~30 seconds downtime). The system is now up and running.

**Comment by janeuhd** [comment]
I'm in. 
The link between specific versioned data sets and the derived state variables is very important. How do we achieve this when uploading the state variables manually (and automatically for that matter)? Is the best solution an additional metadata field in the state variable which lists all available (public and private) dataset where the user can select one or more and hence add the full link to the data to the metadata of the state variable? 
Would it be possible to fill in all the fields in the state variable metadata automatically as soon as the datasets have been selected? E.g. if a new "Associated data" field appear at the top (below title), and the user select dataset X in that field, could then the relevant fields below be autofilled, so that the user only needs to go through and fill then ones that cannot be filled automatically?

**Comment by frafra** [comment]
I think that having a multiple selection searchable list as for other fields would make a lot of sense. I am going to add it in a moment.
Auto-fill is possible, but manual edit of the automatically-filled fields will be locked/hidden when adding or changing a state-variables dataset. Would it be OK for you?

**Comment by janeuhd** [comment]
That manual edit is locked is not a problem if we find sufficiently good rules for the auto-filling. If this turns out to be difficult for some fields, it would be better to skip the autofill and have a mandatory manual fill instead. I can do a bit of testing as soon as the select data field and autofill is in place.

**Comment by frafra** [comment]
Autocompletion status:
- [X] embargo
- [X] visibility
- [X] start date
- [X] end date
- [X] geographic location
- [X] scientific name
- [ ] tags
- [ ] associated parties
- [ ] persons
- [ ] contact persons
- [ ] resource citation
- [ ] organization name

**Comment by frafra** [comment]
Deployed on coatdemo.
I will wait for feedback. If no major issues are encounter and we just have minor changes left (text, labels, fields to be removed o slightly variations) we could deploy it in production tomorrow after an additional test on our side too.
