### ISSUE TITLE
Dataset counter on group not updated

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#8]
When I add a dataset to a group, the ‘counter’ (of the total number of datasets in a group) is not updated. It works for Organizations, not for Groups.

**Comment by frafra** [comment]
Counters could report different number if they are considering each versioned dataset individually or grouped by dataset `base_name`.

This kind of issue should probably be fixed in `ckanext-datasetversions`, but it looks unmaintained, so we have our custom version (temporary stored in my personal profile on github).

**Comment by mdlux** [comment]
Since we are switching to Organizations, and groups will be disabled, this issue is not anymore relevant.  closing
